export const AUTH_REGISTER = "AUTH_REGISTER";

export const USER_UPDATE = "USER_UPDATE";
export const USER_DELETE = "USER_DELETE";
export const USER_RATE = "USER_RATE";
export const USER_UPGRADE_REQUEST = "USER_UPGRADE_REQUEST";
export const USER_UPDATE_ROLE = "USER_UPDATE_ROLE";

export const CATEGORY_LIST_UPDATE = "CATEGORY_LIST_UPDATE";

export const PRODUCT_ADD = "PRODUCT_ADD";
export const PRODUCT_DELETE = "PRODUCT_DELETE";
export const PRODUCT_APPEND_DESCRIPTION = "PRODUCT_APPEND_DESCRIPTION";
export const PRODUCT_ADD_WATCHLIST = "PRODUCT_ADD_WATCHLIST";
export const PRODUCT_DELETE_WATCHLIST = "PRODUCT_DELETE_WATCHLIST";
export const PRODUCT_WON = "PRODUCT_WON";

export const BIDDING_ADD = "BIDDING_ADD";
export const BIDDING_ADD_AUTO = "BIDDING_ADD_AUTO";
export const BIDDING_BUY = "BIDDING_BUY";
export const BIDDING_REQUEST_ADD = "BIDDING_REQUEST_ADD";
export const BIDDING_PERMISSION_UPDATE = "BIDDING_PERMISSION_UPDATE";
export const BIDDING_REJECT = "BIDDING_REJECT";
